### ISSUE TITLE
Breadcrumb Issue

### ISSUE THREAD

**Issue by aerni** [justkidding96/statamic-aardvark-seo#68] opened 2020-12-30 13:40 UTC
I'm getting a Google Search Console error concerning my website's Breadcrumbs. It's saying, that the item's name is missing. The error only occurs in a multi-site on a non-default locale.

```js
// Default English Locale

{
  "@type": "BreadcrumbList",
  "itemListElement": [{ 
    "@type": "ListItem", 
    "position": 1,
    "item": {
      "@type": "Thing",
      "name":"Home",
      "id": "https:\/\/michaelaerni.ch\/en"
    }
  }]
}


// German Locale

{
  "@type": "BreadcrumbList",
  "itemListElement": [{ 
    "@type": "ListItem", 
    "position": 1,
    "item": {
      "@type": "Thing",
      "id": "https:\/\/michaelaerni.ch\/de"
    }
  }]
}
```

The `name` key is missing in the `item` object in the German locale.

**Comment by AndrewHaine** [comment] 2021-01-25 09:27
Hi @aerni ,

I've just released 2.0.7 which should fix the issues we're having with multisite breadcrumbs :)

**Comment by LorensoD** [comment] 2021-05-17 11:22
I'm still experiencing this issue

```
// Default English Locale: https://eventix.io/help/my-ticket-revenue

{
   "@type":"ListItem",
   "position":2,
   "item":{
      "@type":"Thing",
      "name":"Help",
      "id":"https:\/\/eventix.io\/help"
   }
}

// Dutch Locale: https://eventix.nl/help/wanneer-ontvang-ik-mijn-ticketomzet

{
   "@type":"ListItem",
   "position":2,
   "item":{
      "@type":"Thing",
      "id":"https:\/\/eventix.nl\/help"
   }
}

```

I'm on `2.0.11`

**Comment by AndrewHaine** [comment] 2021-05-21 09:01
Hey @LorensoD , I'm struggling to replicate this but do think it's something we should look into, please could you send over the markdown files for both language versions of the entry and a copy of your `config/statamic/sites.php` file, please attach them to an email to aardvarkseo@withcandour.co.uk, I'll drop them into a local site and take a look.

**Comment by moritzlang** [comment] 2021-06-17 11:53
Hello @AndrewHaine,

what is the status on this issue?

I am experiencing the same behaviour for the structured breadcrumbs data.
The problem is that the any synced fields (e.g. the title) are not part of the localized entry ([Code](https://github.com/WithCandour/statamic-aardvark-seo/blob/aa7c0cbda2050d3a60e46396ebde3943937c3811/src/Schema/Parts/Breadcrumbs.php#L38)).

A possible solution would be to get the title of the origin through `$entry->origin()->title` when no title is present on the localized entry.

**Comment by AndrewHaine** [comment] 2021-06-17 13:41
HI @moritzlang ,

Brilliant thanks for the spot on this one, I've confirmed that that was the issue and fix on my local multisite setup and that's now been merged and released in 2.0.13. We're still ironing out some of the other multisite bugs and enhancements but hopefully will have more releases out over the next couple of weeks that address those bits.

@LorensoD When possible please could you let me know if this has fixed the issue with the breadcrumbs on your site too and I'll get this issue closed off.

Thanks,
Andrew

**Comment by moritzlang** [comment] 2021-06-17 14:50
@AndrewHaine
Thank you for the fast fix!

**Comment by LorensoD** [comment] 2021-06-18 11:03
@AndrewHaine I can confirm that this fixed the issue with the breadcrumbs on my site. 
@moritzlang Thanks for spotting the problem.

**Closed as completed** 2021-06-22 09:44 UTC
Labels: Bug, Multisite
